# Generated by Django 4.2.1 on 2023-05-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrados',
            fields=[
                ('id_cadastrado', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('nasc', models.TextField(max_length=15)),
                ('idade', models.IntegerField()),
                ('genero', models.TextField(max_length=50)),
                ('naturalidade', models.TextField(max_length=50)),
                ('tempo', models.IntegerField()),
                ('cpf', models.TextField(max_length=11)),
                ('rg', models.TextField(max_length=20)),
                ('nis', models.TextField(max_length=20)),
                ('sus', models.TextField(max_length=20)),
                ('mae', models.TextField(max_length=255)),
                ('pai', models.TextField(max_length=255)),
                ('resp', models.TextField(max_length=255)),
                ('parentesco', models.TextField(max_length=50)),
                ('end', models.TextField(max_length=150)),
                ('bairro', models.TextField(max_length=100)),
                ('cidade', models.TextField(max_length=100)),
                ('estado', models.TextField(max_length=50)),
                ('tel', models.IntegerField()),
                ('cel', models.IntegerField()),
                ('enc', models.TextField(max_length=100)),
                ('motivo', models.TextField(max_length=100)),
            ],
        ),
    ]
