# Generated by Django 4.2.1 on 2023-05-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_cadastrados_nasc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrados',
            old_name='id_cadastrado',
            new_name='id',
        ),
    ]
