# Generated by Django 4.2.1 on 2023-05-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_rename_id_cadastrado_cadastrados_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrados',
            name='nasc',
            field=models.IntegerField(),
        ),
    ]
