# Generated by Django 4.2.1 on 2023-05-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_cadastrados_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrados',
            name='nasc',
            field=models.CharField(max_length=20),
        ),
    ]
